-- V001: Esquema inicial completo
-- users.tenant_id sem FK (adicionada em V002)
-- users.role presente (removida em V003)

CREATE TABLE tenants (
    id           VARCHAR(255) NOT NULL,
    slug         VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    status       VARCHAR(50)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    CONSTRAINT pk_tenants PRIMARY KEY (id),
    CONSTRAINT uq_tenants_slug UNIQUE (slug)
);

CREATE TABLE organization_units (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id VARCHAR(255) NOT NULL,
    parent_id BIGINT,
    name      VARCHAR(255) NOT NULL,
    type      VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_organization_units PRIMARY KEY (id),
    CONSTRAINT fk_ou_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_ou_parent FOREIGN KEY (parent_id) REFERENCES organization_units(id)
);

CREATE TABLE users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id        VARCHAR(255)  NOT NULL,
    email            VARCHAR(255)  NOT NULL,
    nome             VARCHAR(255)  NOT NULL,
    tipo             VARCHAR(50)   NOT NULL,
    cpf              VARCHAR(20),
    cnpj             VARCHAR(20),
    status           VARCHAR(50)   NOT NULL,
    source           VARCHAR(50)   NOT NULL,
    role             VARCHAR(50)   NOT NULL,
    external_id      VARCHAR(255),
    created_at       TIMESTAMP     NOT NULL,
    approved_at      TIMESTAMP,
    rejected_at      TIMESTAMP,
    rejection_reason VARCHAR(1000),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_tenant_email UNIQUE (tenant_id, email)
);

CREATE TABLE user_lifecycles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT       NOT NULL,
    tenant_id  VARCHAR(255) NOT NULL,
    status     VARCHAR(50)  NOT NULL,
    reason     VARCHAR(1000),
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT pk_user_lifecycles PRIMARY KEY (id),
    CONSTRAINT uk_user_lifecycle_user UNIQUE (user_id),
    CONSTRAINT fk_ul_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE memberships (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id              BIGINT       NOT NULL,
    tenant_id            VARCHAR(255) NOT NULL,
    organization_unit_id BIGINT,
    role                 VARCHAR(50)  NOT NULL,
    status               VARCHAR(50)  NOT NULL,
    granted_at           TIMESTAMP    NOT NULL,
    revoked_at           TIMESTAMP,
    CONSTRAINT pk_memberships PRIMARY KEY (id),
    CONSTRAINT fk_membership_user   FOREIGN KEY (user_id)              REFERENCES users(id),
    CONSTRAINT fk_membership_tenant FOREIGN KEY (tenant_id)            REFERENCES tenants(id),
    CONSTRAINT fk_membership_ou     FOREIGN KEY (organization_unit_id) REFERENCES organization_units(id)
);

CREATE TABLE user_audit_entries (
    id             VARCHAR(255) NOT NULL,
    tenant_id      VARCHAR(255) NOT NULL,
    user_id        BIGINT       NOT NULL,
    user_email     VARCHAR(255) NOT NULL,
    actor_id       VARCHAR(255) NOT NULL,
    action         VARCHAR(100) NOT NULL,
    correlation_id VARCHAR(255) NOT NULL,
    details        VARCHAR(1000),
    created_at     TIMESTAMP    NOT NULL,
    CONSTRAINT pk_user_audit_entries PRIMARY KEY (id)
);

CREATE TABLE config_packages (
    id                    VARCHAR(255) NOT NULL,
    scope                 VARCHAR(50)  NOT NULL,
    tenant_id             VARCHAR(255) NOT NULL,
    unit_id               VARCHAR(255),
    role_id               VARCHAR(255),
    user_id               VARCHAR(255),
    device_id             VARCHAR(255),
    updated_at            TIMESTAMP    NOT NULL,
    status                VARCHAR(50)  NOT NULL,
    rollout_activation    VARCHAR(50)  NOT NULL,
    rollout_starts_at     TIMESTAMP,
    rollout_ends_at       TIMESTAMP,
    batch_user_ids_csv    TEXT,
    require_biometric     BOOLEAN,
    camera_min_photos     INT,
    camera_max_photos     INT,
    enable_voice_commands BOOLEAN,
    theme                 VARCHAR(255),
    app_update_channel    VARCHAR(255),
    CONSTRAINT pk_config_packages PRIMARY KEY (id)
);

CREATE TABLE config_audit_entries (
    id         VARCHAR(255) NOT NULL,
    package_id VARCHAR(255) NOT NULL,
    actor_id   VARCHAR(255) NOT NULL,
    actor_role VARCHAR(50)  NOT NULL,
    action     VARCHAR(100) NOT NULL,
    tenant_id  VARCHAR(255) NOT NULL,
    scope      VARCHAR(50)  NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT pk_config_audit_entries PRIMARY KEY (id)
);
