-- V004: Sessao persistida e credenciais internas para auth backend-first
CREATE TABLE user_credentials (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT       NOT NULL,
    tenant_id     VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT pk_user_credentials PRIMARY KEY (id),
    CONSTRAINT uq_user_credentials_user UNIQUE (user_id),
    CONSTRAINT fk_user_credentials_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_credentials_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE sessions (
    id                 VARCHAR(64)  NOT NULL,
    user_id            BIGINT       NOT NULL,
    tenant_id          VARCHAR(255) NOT NULL,
    refresh_token_hash VARCHAR(128) NOT NULL,
    expires_at         TIMESTAMP    NOT NULL,
    revoked_at         TIMESTAMP,
    device_info        VARCHAR(255),
    created_at         TIMESTAMP    NOT NULL,
    CONSTRAINT pk_sessions PRIMARY KEY (id),
    CONSTRAINT uq_sessions_refresh_hash UNIQUE (refresh_token_hash),
    CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_sessions_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);
