-- V007: Core job domain — Demand, InspectionCase, Job, Assignment, Timeline (BOW-120)

CREATE TABLE demands (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    external_id         VARCHAR(128) NOT NULL,
    tenant_id           VARCHAR(255) NOT NULL,
    source              VARCHAR(80)  NOT NULL,
    normalized_payload  TEXT         NOT NULL,
    status              VARCHAR(50)  NOT NULL,
    created_at          TIMESTAMP    NOT NULL,
    CONSTRAINT pk_demands PRIMARY KEY (id),
    CONSTRAINT uq_demands_external_tenant UNIQUE (external_id, tenant_id),
    CONSTRAINT fk_demands_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE inspection_cases (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    demand_id        BIGINT,
    tenant_id        VARCHAR(255) NOT NULL,
    number           VARCHAR(80)  NOT NULL,
    property_address VARCHAR(500) NOT NULL,
    inspection_type  VARCHAR(80)  NOT NULL,
    deadline         TIMESTAMP,
    status           VARCHAR(50)  NOT NULL,
    created_at       TIMESTAMP    NOT NULL,
    CONSTRAINT pk_inspection_cases PRIMARY KEY (id),
    CONSTRAINT uq_case_number_tenant UNIQUE (number, tenant_id),
    CONSTRAINT fk_case_demand FOREIGN KEY (demand_id) REFERENCES demands(id),
    CONSTRAINT fk_case_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE jobs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    case_id      BIGINT       NOT NULL,
    tenant_id    VARCHAR(255) NOT NULL,
    org_unit_id  BIGINT,
    title        VARCHAR(255) NOT NULL,
    status       VARCHAR(50)  NOT NULL,
    assigned_to  BIGINT,
    deadline_at  TIMESTAMP,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    CONSTRAINT pk_jobs PRIMARY KEY (id),
    CONSTRAINT fk_jobs_case FOREIGN KEY (case_id) REFERENCES inspection_cases(id),
    CONSTRAINT fk_jobs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE assignments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id       BIGINT       NOT NULL,
    user_id      BIGINT       NOT NULL,
    tenant_id    VARCHAR(255) NOT NULL,
    offered_at   TIMESTAMP    NOT NULL,
    responded_at TIMESTAMP,
    response     VARCHAR(20),
    CONSTRAINT pk_assignments PRIMARY KEY (id),
    CONSTRAINT fk_assignments_job FOREIGN KEY (job_id) REFERENCES jobs(id),
    CONSTRAINT fk_assignments_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE job_timeline_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id      BIGINT        NOT NULL,
    from_status VARCHAR(50)   NOT NULL,
    to_status   VARCHAR(50)   NOT NULL,
    actor_id    VARCHAR(255),
    reason      VARCHAR(1000),
    occurred_at TIMESTAMP     NOT NULL,
    CONSTRAINT pk_job_timeline_entries PRIMARY KEY (id),
    CONSTRAINT fk_timeline_job FOREIGN KEY (job_id) REFERENCES jobs(id)
);
