-- V009: Persist mobile inspection submissions with idempotency and job linkage
CREATE TABLE inspection_submissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id          BIGINT       NOT NULL,
    tenant_id       VARCHAR(255) NOT NULL,
    vistoriador_id  BIGINT       NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    protocol_id     VARCHAR(80)  NOT NULL,
    status          VARCHAR(40)  NOT NULL,
    payload_json    TEXT         NOT NULL,
    submitted_at    TIMESTAMP    NOT NULL,
    CONSTRAINT pk_inspection_submissions PRIMARY KEY (id),
    CONSTRAINT uq_inspection_submissions_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT uq_inspection_submissions_protocol UNIQUE (protocol_id),
    CONSTRAINT fk_inspection_submissions_job FOREIGN KEY (job_id) REFERENCES jobs(id),
    CONSTRAINT fk_inspection_submissions_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);
