-- V010: Canonical NBR sections for mobile check-in config
CREATE TABLE checkin_sections (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tenant_id          VARCHAR(255) NOT NULL,
    tipo_imovel        VARCHAR(80),
    section_key        VARCHAR(80)  NOT NULL,
    section_label      VARCHAR(255) NOT NULL,
    mandatory          BOOLEAN      NOT NULL,
    photo_min          INT          NOT NULL,
    photo_max          INT          NOT NULL,
    desired_items_json TEXT         NOT NULL,
    sort_order         INT          NOT NULL,
    active             BOOLEAN      NOT NULL,
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL,
    CONSTRAINT pk_checkin_sections PRIMARY KEY (id)
);

CREATE INDEX idx_checkin_sections_tenant_active ON checkin_sections (tenant_id, active, sort_order);
