-- V011: Explicit Inspection aggregate persisted from mobile submissions
CREATE TABLE inspections (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    submission_id      BIGINT,
    job_id             BIGINT       NOT NULL,
    tenant_id          VARCHAR(255) NOT NULL,
    vistoriador_id     BIGINT       NOT NULL,
    idempotency_key    VARCHAR(255) NOT NULL,
    protocol_id        VARCHAR(80)  NOT NULL,
    status             VARCHAR(40)  NOT NULL,
    payload_json       CLOB         NOT NULL,
    submitted_at       TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL,
    CONSTRAINT pk_inspections PRIMARY KEY (id),
    CONSTRAINT uq_inspections_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT uq_inspections_protocol UNIQUE (protocol_id),
    CONSTRAINT fk_inspections_submission FOREIGN KEY (submission_id) REFERENCES inspection_submissions(id),
    CONSTRAINT fk_inspections_job FOREIGN KEY (job_id) REFERENCES jobs(id)
);

CREATE INDEX idx_inspections_tenant_status_submitted ON inspections (tenant_id, status, submitted_at);
