CREATE TABLE valuation_processes (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    inspection_id        BIGINT       NOT NULL,
    tenant_id            VARCHAR(255) NOT NULL,
    status               VARCHAR(50)  NOT NULL,
    method               VARCHAR(80)  NOT NULL,
    assigned_analyst_id  BIGINT,
    created_at           TIMESTAMP    NOT NULL,
    updated_at           TIMESTAMP    NOT NULL,
    CONSTRAINT pk_valuation_processes PRIMARY KEY (id),
    CONSTRAINT uq_valuation_process_inspection UNIQUE (inspection_id),
    CONSTRAINT fk_valuation_process_inspection FOREIGN KEY (inspection_id) REFERENCES inspections(id) ON DELETE CASCADE,
    CONSTRAINT fk_valuation_process_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE INDEX idx_valuation_process_tenant_status ON valuation_processes (tenant_id, status, updated_at);

CREATE TABLE intake_validations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    valuation_process_id  BIGINT       NOT NULL,
    validated_by          BIGINT,
    issues_json           TEXT,
    notes                 TEXT,
    validated_at          TIMESTAMP    NOT NULL,
    result                VARCHAR(30)  NOT NULL,
    CONSTRAINT pk_intake_validations PRIMARY KEY (id),
    CONSTRAINT fk_intake_validation_process FOREIGN KEY (valuation_process_id) REFERENCES valuation_processes(id) ON DELETE CASCADE
);

CREATE INDEX idx_intake_validations_process ON intake_validations (valuation_process_id, validated_at);

CREATE TABLE reports (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    valuation_process_id  BIGINT       NOT NULL,
    tenant_id             VARCHAR(255) NOT NULL,
    status                VARCHAR(50)  NOT NULL,
    generated_by          VARCHAR(255),
    approved_by           VARCHAR(255),
    review_notes          TEXT,
    content_json          TEXT         NOT NULL,
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP    NOT NULL,
    CONSTRAINT pk_reports PRIMARY KEY (id),
    CONSTRAINT uq_reports_process UNIQUE (valuation_process_id),
    CONSTRAINT fk_reports_process FOREIGN KEY (valuation_process_id) REFERENCES valuation_processes(id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE INDEX idx_reports_tenant_status ON reports (tenant_id, status, updated_at);
