export type UiLanguage = "pt" | "en";

export function resolveUiLanguage(): UiLanguage {
  if (typeof navigator === "undefined") return "pt";
  const language = navigator.language.toLowerCase();
  return language.startsWith("en") ? "en" : "pt";
}

const DICTIONARY = {
  pt: {
    multiScopeResolution: "Resolucao de configuracao multi-escopo",
    precedenceSimulation:
      "Simulacao de precedencia: global -> tenant -> role -> user -> device.",
    operationalProfile: "Perfil operacional",
    user: "Usuario",
    device: "Dispositivo",
    publishConfigPackage: "Publicar pacote de configuracao",
    updateChannel: "Canal de update",
    activation: "Ativacao",
    start: "Inicio",
    end: "Fim",
    batchUsers: "Lote de usuarios",
    enableVoiceCommands: "Habilitar comandos de voz",
    packageCatalog: "Catalogo de pacotes",
    appliedPackages: "Pacotes aplicados",
    scope: "Escopo",
    canonicalInspectionTree: "Arvore canonica da vistoria",
    canonicalTreeDescription:
      "A arvore define a hierarquia real do menu da vistoria. Tipo, Subtipo e Area da Foto orientam o inicio do fluxo. Ambiente, Elemento, Material e Estado organizam a captura e a classificacao.",
    photoArea: "Area da Foto",
    showAll: "Mostrar todas",
    currentContext: "Contexto atual",
    currentTree: "Arvore atual",
    fullTree: "Arvore completa",
    fullTreeDescription:
      "Visualizacao do ramo inteiro por tipo, subtipo e contexto.",
    selectedItemProperties: "Propriedades do item selecionado",
    selectedItemDescription: "Leitura operacional do no atual.",
    label: "Rotulo",
    saveLabel: "Salvar rotulo",
    level: "Nivel",
    path: "Caminho",
    visible: "Visivel",
    required: "Obrigatorio",
    minPhotos: "Min Fotos",
    maxPhotos: "Max Fotos",
    noSelectedItem: "Nenhum item selecionado.",
    checkInStep1: "Check-in etapa 1",
    checkInStep1Description:
      "Aqui voce parametriza o que aparece na primeira tela do app e como o usuario chega na camera.",
    initialInspectionData: "Dados iniciais da vistoria",
    objectAndClientSection: "Sessao Dados do objeto e cliente",
    gpsConfirmation: "GPS confirmacao",
    whatsappButton: "Botao WhatsApp",
    callButton: "Botao Ligar",
    checkInStep1Stage: "Etapa 1 do check-in",
    customerPresent: "Cliente esta presente",
    confirmAndOpenCameraButton: "Botao Confirmar e abrir a camera",
    checkInStep2: "Check-in etapa 2",
    checkInStep2Description:
      "Esta tela e opcional no app. Aqui ficam os registros fotograficos exigidos e os grupos de qualificacao complementar da vistoria.",
    step2Inspection: "Etapa 2 Vistoria",
    canonicalType: "Tipo canonico",
    allowsCapture: "Permite captura",
    photoRecord: "Registro Fotografico",
    photoRecordDescription:
      "Agrupa os registros obrigatorios ou desejaveis que alimentam a captura.",
    infrastructureServices: "Infraestrutura e Servicos",
    infrastructureServicesDescription:
      "Agrupa niveis de qualificacao complementar exibidos no app.",
    addGroup: "Adicionar grupo",
    removeType: "Remover tipo",
    enableCamera: "Habilita camera",
    publishForApproval: "Publicar para aprovacao",
    recentAudit: "Auditoria recente",
    listPackagesFailed: "Falha ao listar pacotes",
    auditLoadFailed: "Falha na auditoria",
    resolveLoadFailed: "Falha no resolve",
    authenticatedSessionLoadFailed: "Erro ao carregar sessao autenticada",
    unidentifiedError: "Erro nao identificado",
    authenticatedTenantNotLoaded: "Tenant autenticado ainda nao carregado.",
    publishPackageFailed: "Falha ao publicar pacote",
    rollbackPackageFailed: "Falha ao reverter pacote",
    approvePackageFailed: "Falha ao aprovar pacote",
    publishing: "Publicando...",
    inspectionsReceived: "Inspections recebidas",
    inspectionsSubtitle: "Painel operacional com filtros e detalhe tecnico de payload.",
    backToDashboard: "Voltar ao dashboard",
    totalFiltered: "Total do filtro",
    receivedTodayPage: "Recebidas hoje (pagina)",
    pendingIntake: "Pendentes de intake",
    syncErrors: "Erros de sincronizacao",
    status: "Status",
    from: "De",
    to: "Ate",
    fieldAgent: "Field Agent",
    pageSize: "Tamanho da pagina",
    applyFilters: "Aplicar filtros",
    previous: "Anterior",
    next: "Proxima",
    loadingInspections: "Carregando inspections...",
    detail: "Detalhe",
    noInspectionsForFilters: "Nenhuma inspection encontrada para os filtros atuais.",
    technicalDetail: "Detalhe tecnico",
    loadingDetail: "Carregando detalhe...",
    selectInspectionForPayload: "Selecione uma inspection para visualizar o payload completo.",
    queryInspectionsFailed: "Falha ao consultar inspections",
    unexpectedLoadInspections: "Erro inesperado ao carregar inspections",
    queryDetailFailed: "Falha ao consultar detalhe",
    unexpectedLoadDetail: "Erro inesperado ao carregar detalhe",
  },
  en: {
    multiScopeResolution: "Multi-scope configuration resolution",
    precedenceSimulation:
      "Precedence simulation: global -> tenant -> role -> user -> device.",
    operationalProfile: "Operational profile",
    user: "User",
    device: "Device",
    publishConfigPackage: "Publish configuration package",
    updateChannel: "Update channel",
    activation: "Activation",
    start: "Start",
    end: "End",
    batchUsers: "User batch",
    enableVoiceCommands: "Enable voice commands",
    packageCatalog: "Package catalog",
    appliedPackages: "Applied packages",
    scope: "Scope",
    canonicalInspectionTree: "Inspection canonical tree",
    canonicalTreeDescription:
      "The tree defines the real hierarchy of the inspection menu. Type, Subtype and Photo Area drive the start of the flow. Environment, Element, Material and Condition organize capture and classification.",
    photoArea: "Photo Area",
    showAll: "Show all",
    currentContext: "Current context",
    currentTree: "Current tree",
    fullTree: "Full tree",
    fullTreeDescription:
      "View the entire branch by type, subtype and context.",
    selectedItemProperties: "Selected item properties",
    selectedItemDescription: "Operational reading of the current node.",
    label: "Label",
    saveLabel: "Save label",
    level: "Level",
    path: "Path",
    visible: "Visible",
    required: "Required",
    minPhotos: "Min Photos",
    maxPhotos: "Max Photos",
    noSelectedItem: "No selected item.",
    checkInStep1: "Check-in step 1",
    checkInStep1Description:
      "Configure what appears on the app first screen and how the user reaches the camera.",
    initialInspectionData: "Initial inspection data",
    objectAndClientSection: "Object and client section",
    gpsConfirmation: "GPS confirmation",
    whatsappButton: "WhatsApp button",
    callButton: "Call button",
    checkInStep1Stage: "Check-in step 1 stage",
    customerPresent: "Customer is present",
    confirmAndOpenCameraButton: "Confirm and open camera button",
    checkInStep2: "Check-in step 2",
    checkInStep2Description:
      "This screen is optional in the app. It contains required photo records and complementary qualification groups.",
    step2Inspection: "Step 2 inspection",
    canonicalType: "Canonical type",
    allowsCapture: "Allows capture",
    photoRecord: "Photo record",
    photoRecordDescription:
      "Groups required or desired records that feed capture.",
    infrastructureServices: "Infrastructure and services",
    infrastructureServicesDescription:
      "Groups complementary qualification levels shown in the app.",
    addGroup: "Add group",
    removeType: "Remove type",
    enableCamera: "Enable camera",
    publishForApproval: "Publish for approval",
    recentAudit: "Recent audit",
    listPackagesFailed: "Failed to list packages",
    auditLoadFailed: "Failed to load audit",
    resolveLoadFailed: "Failed to resolve config",
    authenticatedSessionLoadFailed: "Failed to load authenticated session",
    unidentifiedError: "Unidentified error",
    authenticatedTenantNotLoaded: "Authenticated tenant is not loaded yet.",
    publishPackageFailed: "Failed to publish package",
    rollbackPackageFailed: "Failed to roll back package",
    approvePackageFailed: "Failed to approve package",
    publishing: "Publishing...",
    inspectionsReceived: "Received inspections",
    inspectionsSubtitle: "Operational panel with filters and technical payload detail.",
    backToDashboard: "Back to dashboard",
    totalFiltered: "Filtered total",
    receivedTodayPage: "Received today (page)",
    pendingIntake: "Pending intake",
    syncErrors: "Sync errors",
    status: "Status",
    from: "From",
    to: "To",
    fieldAgent: "Field agent",
    pageSize: "Page size",
    applyFilters: "Apply filters",
    previous: "Previous",
    next: "Next",
    loadingInspections: "Loading inspections...",
    detail: "Detail",
    noInspectionsForFilters: "No inspection found for the current filters.",
    technicalDetail: "Technical detail",
    loadingDetail: "Loading detail...",
    selectInspectionForPayload: "Select an inspection to view the full payload.",
    queryInspectionsFailed: "Failed to query inspections",
    unexpectedLoadInspections: "Unexpected error while loading inspections",
    queryDetailFailed: "Failed to query detail",
    unexpectedLoadDetail: "Unexpected error while loading detail",
  },
} as const;

export function t(
  language: UiLanguage,
  key: keyof typeof DICTIONARY.pt,
): string {
  return DICTIONARY[language][key];
}
